#!/usr/bin/env python3

from os import listdir, system

DEV_PATH = "/dev/"

if __name__ == '__main__':
    devices = [f for f in listdir(DEV_PATH) if "tty.usbserial-" in f]

    # Sort the devices in reverse order 
    devices.reverse()

    print("Serial devices:")
    print("---------------")

    for i, d in enumerate(devices):
        print(str(i) + ") " + d)

    choice_s = input("Choice [0]: ")

    if choice_s == "":
        choice = 0
    else:
        try:
            choice = int(choice_s)
        except:
            exit(0)

    system("screen " + DEV_PATH + devices[choice] + " 115200")

